# Generated by Django 5.0.7 on 2024-08-02 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consignataria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=256)),
                ("cpf_cnpj", models.CharField(max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Servidor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("matricula", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConsultaMargemAthenas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cadastrado_em", models.DateTimeField(auto_now_add=True, null=True)),
                ("modificado_em", models.DateTimeField(auto_now=True, null=True)),
                ("desativado_em", models.DateTimeField(blank=True, null=True)),
                ("margem_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "margem_disponivel",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cadastrado_por",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consignataria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contrib.consignataria",
                    ),
                ),
                (
                    "desativado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_desativado_por",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modificado_por",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "servidor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contrib.servidor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cadastrado_em", models.DateTimeField(auto_now_add=True, null=True)),
                ("modificado_em", models.DateTimeField(auto_now=True, null=True)),
                ("desativado_em", models.DateTimeField(blank=True, null=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prazo_inicial", models.DateTimeField()),
                ("prazo_final", models.DateTimeField()),
                (
                    "situacao",
                    models.SmallIntegerField(
                        choices=[
                            (0, "EM ANALISE"),
                            (1, "DEFERIDO"),
                            (2, "INDEFERIDO"),
                            (3, "EXPIRADO"),
                        ],
                        default=0,
                    ),
                ),
                ("contrato", models.CharField(max_length=255, unique=True)),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cadastrado_por",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contrib.consultamargemathenas",
                    ),
                ),
                (
                    "desativado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_desativado_por",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modificado_por",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
