# Generated by Django 5.0.8 on 2024-08-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contrib", "0002_consignataria_cadastrado_em_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="situacao",
            field=models.SmallIntegerField(
                choices=[
                    (0, "EM ANÁLISE"),
                    (1, "DEFERIDO"),
                    (2, "INDEFERIDO"),
                    (3, "EXPIRADO"),
                ],
                default=0,
            ),
        ),
    ]
