# Generated by Django 5.0.8 on 2024-09-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contrib", "0004_reserva_carencia_dias_reserva_cet_reserva_cpf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
